version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: neuroq_postgres
    environment:
      POSTGRES_DB: neuroq_db
      POSTGRES_USER: neuroq_user
      POSTGRES_PASSWORD: neuroq_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - neuroq_network

  # Redis for caching and rate limiting
  redis:
    image: redis:7-alpine
    container_name: neuroq_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - neuroq_network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: neuroq_backend
    environment:
      - DATABASE_URL=postgresql://neuroq_user:neuroq_password@postgres:5432/neuroq_db
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=your-secret-key-change-in-production
      - DEBUG=False
      - HOST=0.0.0.0
      - PORT=8000
      - CORS_ORIGINS=http://localhost:3000,http://localhost:3001
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./ai_models:/app/ai_models
    networks:
      - neuroq_network
    restart: unless-stopped

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: neuroq_frontend
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - neuroq_network
    restart: unless-stopped

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    container_name: neuroq_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    networks:
      - neuroq_network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  neuroq_network:
    driver: bridge
